# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_login = QtWidgets.QFrame(self.centralwidget)
        self.frame_login.setEnabled(True)
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.label_title = QtWidgets.QLabel(self.frame_login)
        self.label_title.setGeometry(QtCore.QRect(430, 140, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.PlainText)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_username = QtWidgets.QLabel(self.frame_login)
        self.label_username.setGeometry(QtCore.QRect(320, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.frame_login)
        self.label_password.setGeometry(QtCore.QRect(320, 390, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.textEdit_username = QtWidgets.QTextEdit(self.frame_login)
        self.textEdit_username.setGeometry(QtCore.QRect(460, 280, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.textEdit_username.setFont(font)
        self.textEdit_username.setObjectName("textEdit_username")
        self.textEdit_password = QtWidgets.QTextEdit(self.frame_login)
        self.textEdit_password.setGeometry(QtCore.QRect(460, 380, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.textEdit_password.setFont(font)
        self.textEdit_password.setObjectName("textEdit_password")
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_cancel.setGeometry(QtCore.QRect(390, 480, 111, 41))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_login.setGeometry(QtCore.QRect(660, 480, 111, 41))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_error = QtWidgets.QLabel(self.frame_login)
        self.label_error.setGeometry(QtCore.QRect(390, 220, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.frame_login)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 21))
        self.menubar.setObjectName("menubar")
        self.menuAccess_Control = QtWidgets.QMenu(self.menubar)
        self.menuAccess_Control.setObjectName("menuAccess_Control")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuBuilding_Manage = QtWidgets.QMenu(self.menuOption)
        self.menuBuilding_Manage.setObjectName("menuBuilding_Manage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionDoor_Manage = QtWidgets.QAction(MainWindow)
        self.actionDoor_Manage.setObjectName("actionDoor_Manage")
        self.actionPeople_Manage = QtWidgets.QAction(MainWindow)
        self.actionPeople_Manage.setObjectName("actionPeople_Manage")
        self.actionGuest_Manage = QtWidgets.QAction(MainWindow)
        self.actionGuest_Manage.setObjectName("actionGuest_Manage")
        self.actionImage_Manage = QtWidgets.QAction(MainWindow)
        self.actionImage_Manage.setObjectName("actionImage_Manage")
        self.actionApartment_Manage_2 = QtWidgets.QAction(MainWindow)
        self.actionApartment_Manage_2.setObjectName("actionApartment_Manage_2")
        self.actionOffice_Manage = QtWidgets.QAction(MainWindow)
        self.actionOffice_Manage.setObjectName("actionOffice_Manage")
        self.actionApartment_Manage_3 = QtWidgets.QAction(MainWindow)
        self.actionApartment_Manage_3.setObjectName("actionApartment_Manage_3")
        self.menuAccess_Control.addSeparator()
        self.menuAccess_Control.addAction(self.actionLogin)
        self.menuAccess_Control.addAction(self.actionLogout)
        self.menuBuilding_Manage.addAction(self.actionApartment_Manage_2)
        self.menuBuilding_Manage.addAction(self.actionOffice_Manage)
        self.menuBuilding_Manage.addAction(self.actionApartment_Manage_3)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.menuBuilding_Manage.menuAction())
        self.menuOption.addAction(self.actionDoor_Manage)
        self.menuOption.addAction(self.actionPeople_Manage)
        self.menuOption.addAction(self.actionGuest_Manage)
        self.menuOption.addAction(self.actionImage_Manage)
        self.menubar.addAction(self.menuAccess_Control.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "LOGIN"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.menuAccess_Control.setTitle(_translate("MainWindow", "Session"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuBuilding_Manage.setTitle(_translate("MainWindow", "Building Manage"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionDoor_Manage.setText(_translate("MainWindow", "Door Manage"))
        self.actionPeople_Manage.setText(_translate("MainWindow", "Resident Manage"))
        self.actionGuest_Manage.setText(_translate("MainWindow", "Guest Manage"))
        self.actionImage_Manage.setText(_translate("MainWindow", "Image Manage"))
        self.actionApartment_Manage_2.setText(_translate("MainWindow", "Block Manage"))
        self.actionOffice_Manage.setText(_translate("MainWindow", "Office Manage"))
        self.actionApartment_Manage_3.setText(_translate("MainWindow", "Apartment Manage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

